### ISSUE TITLE
Integrate UploadPhoto into CreateTaskScreen and reach successful POST of all new task Data

### ISSUE THREAD

**Issue by futurethang** [UWBC-Final-Project/Neighbor-Corps-React-Native#12]
They are currently separate components and should all execute as a single user operation.

**Comment by futurethang** [comment]
Almost done! Just needs Position Data to send also

**Comment by phoebe1002** [comment]
working on add position, see #29

**Comment by phoebe1002** [comment]
#29 is getting done, will add #23 that will allow users to drop pin/marker

**Comment by phoebe1002** [comment]
implemented, see #42 
next step: improve the UX

**Comment by phoebe1002** [comment]
on production!
