### ISSUE TITLE
Create 'Select location by pin drop' screen/function so users can add tasks from gallery instead of camera.

### ISSUE THREAD

**Issue by futurethang** [UWBC-Final-Project/Neighbor-Corps-React-Native#23]
Currently the app defaults to assuming a task is created in real-time, getting the photo and the GPS coords together. However in order to allow submission from a gallery shot, the need to add a screen that allows user to drop a pin on a map to indicate the issue site when not at the physical location.

**Comment by phoebe1002** [comment]
implemented, see pull request #39

**Comment by phoebe1002** [comment]
implemented, see pull request #39
